name: Myoji CI/CD test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up python base
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install requirements
      run: make install
    - name: Lint
      run: make lint
    - name: Test
      run: make test
